apiVersion: v2
appVersion: v2.1.11
description: A Helm chart for Kubernetes
name: zot
type: application
version: 2.4.0
keywords:
- kubernetes-zot-registry
- oci-registry
home: https://github.com/giantswarm/zot
icon: https://s.giantswarm.io/app-icons/zot/1/light.svg
annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'false'
  io.giantswarm.application.restrictions.namespace-singleton: 'false'
  io.giantswarm.application.team: honeybadger
upstreamChartVersion: 0.1.91
